# Generated by Django 5.2.7 on 2025-11-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_campus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='name',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='campus',
            name='cn_name',
            field=models.CharField(default='an', max_length=200),
            preserve_default=False,
        ),
    ]
