# Generated by Django 5.2.7 on 2025-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_name_campus_en_name_campus_cn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='cn_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
