# Generated by Django 5.2.7 on 2025-11-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_campus_cn_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='preferedLanguage',
        ),
    ]
